### ISSUE TITLE
[BUG] TypeError: dataclass() got an unexpected keyword argument 'slots'

### ISSUE THREAD

**Issue by AgentT30** [bhavnicksm/chonkie#33]
**Describe the bug**
When I do a `from chonkie import TokenChunker` I get the error

**To Reproduce**
Run `from chonkie import TokenChunker` after a fresh install

**Expected behavior**
The TokenChunker package should be imported without errors

**Screenshots**
```
Downloading chonkie-0.2.0-py3-none-any.whl (23 kB)
Downloading autotiktokenizer-0.2.1-py3-none-any.whl (8.9 kB)
Installing collected packages: autotiktokenizer, chonkie
Successfully installed autotiktokenizer-0.2.1 chonkie-0.2.0
(.llm_vnev) mis@mispl-lap-163:~ $ python3
Python 3.8.10 (default, Sep 11 2024, 16:02:53) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from chonkie import TokenChunker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mis/Documents/docxtract/llm/.llm_vnev/lib/python3.8/site-packages/chonkie/__init__.py", line 1, in <module>
    from .chunker import (BaseChunker, Chunk, SDPMChunker, SemanticChunk,
  File "/home/mis/Documents/docxtract/llm/.llm_vnev/lib/python3.8/site-packages/chonkie/chunker/__init__.py", line 1, in <module>
    from .base import BaseChunker, Chunk
  File "/home/mis/Documents/docxtract/llm/.llm_vnev/lib/python3.8/site-packages/chonkie/chunker/base.py", line 9, in <module>
    @dataclass(slots=True)
TypeError: dataclass() got an unexpected keyword argument 'slots'
```

**Additional context**
Did a fresh install using `pip install chonkie` and tried to run the tool based on the given guide.

Anything that I did is wrong?

**Comment by bhavnicksm** [comment]
Hey @AgentT30!

Thanks for raising an issue 😊

The issue is with Python slots, which were introduced first in python3.10 as the parameter that I am using inside the `dataclass`. Before that, it was `__slots__` for versions 3.8 and 3.9, which needs to be added in the codebase.

It seems like it got missed as an error. As a workaround for now, could you try it with Python 3.10? 

I'll add a backward compatible version of slots into Chonkie in a patch release as soon as possible.

Thanks!
