### ISSUE TITLE
[FEAT] Min chunk size (for semantic chunkers)

### ISSUE THREAD

**Issue by kbarendrecht** [bhavnicksm/chonkie#40]
**Checklist**
Before you begin, please make sure of the following points:
- [x] This feature is not implemented yet in the library in any form
- [x] This feature has not been suggested previously
- [x] This feature is relevant to the library

**Describe the solution you'd like**
Using SPDM chunker with `SentenceTransformer('all-MiniLM-L6-v2')` the generated chunks are (arguably) better than using a constant size with floating window or recursive approach. But now and then it makes a tiny chunk. Setting a min chunk size could combat this problem at the cost of making the next chunk somewhat worse. 

**Additional context**
I used a very low sentence similary score (0.1 using all-MiniLM-L6-v2), even still it the model generated tiny chunks together with rather large chunks.
![image](https://github.com/user-attachments/assets/1c8ab9e5-e91f-411e-9cb6-0955dad4f1cb)

EDIT: Now that I check my post, It might have to do with thinking that `5.3.` is two sentences; '5' and '2', which are not similar at all to the rest of the content.

**Comment by bhavnicksm** [comment]
Hey @kbarendrecht! 

Thanks for submitting the issue 😊

That does seem odd! Yes, chunks should not be broken down like that into ultra-small pieces. It's possibly due to decimal points being there inside the smaller chunks.

I will look into this and get back to you once I have a fix for this...

It would be really helpful if you could provide an example text you see the same issue on~~ It would help me in building tests which I could use for TDD.

Thanks!

**Comment by bhavnicksm** [comment]
Hey @kbarendrecht!

Thanks for being patient with this, the new release `v0.2.1.post1` adds support for `min_chunk_size` as provided in the suggestions!

I hope this helps out, closing the issue with this.

Thanks!
